// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJSrkYDVhqtCn6wUqtGjOIycHMaTrZF34',
    appId: '1:835797323230:web:2385cb24ea20c96655a14f',
    messagingSenderId: '835797323230',
    projectId: 'garage-week-bintech',
    authDomain: 'garage-week-bintech.firebaseapp.com',
    storageBucket: 'garage-week-bintech.appspot.com',
    measurementId: 'G-NHD971T94F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt563kTgFEGkPr6sioD0itcX_rTj3Kh7o',
    appId: '1:835797323230:android:984eb8cd1555ee7455a14f',
    messagingSenderId: '835797323230',
    projectId: 'garage-week-bintech',
    storageBucket: 'garage-week-bintech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnrSpA6TUDb7_waxLxLTAtAxhH8MvdbPM',
    appId: '1:835797323230:ios:1f76cb62cec8211655a14f',
    messagingSenderId: '835797323230',
    projectId: 'garage-week-bintech',
    storageBucket: 'garage-week-bintech.appspot.com',
    iosBundleId: 'com.bintech.garageWeek2024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnrSpA6TUDb7_waxLxLTAtAxhH8MvdbPM',
    appId: '1:835797323230:ios:1f76cb62cec8211655a14f',
    messagingSenderId: '835797323230',
    projectId: 'garage-week-bintech',
    storageBucket: 'garage-week-bintech.appspot.com',
    iosBundleId: 'com.bintech.garageWeek2024',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJSrkYDVhqtCn6wUqtGjOIycHMaTrZF34',
    appId: '1:835797323230:web:0e8452e72d9773f155a14f',
    messagingSenderId: '835797323230',
    projectId: 'garage-week-bintech',
    authDomain: 'garage-week-bintech.firebaseapp.com',
    storageBucket: 'garage-week-bintech.appspot.com',
    measurementId: 'G-CPK2DSF75K',
  );

}